CREATE TABLE IF NOT EXISTS public."People"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    last_updated timestamp without time zone DEFAULT now(),
    first_name text COLLATE pg_catalog."default",
    last_name text COLLATE pg_catalog."default",
    short_name text COLLATE pg_catalog."default",
    sms_number bigint,
    email_address text COLLATE pg_catalog."default",
    comment text COLLATE pg_catalog."default",
    CONSTRAINT "People_pkey" PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public."People"
    OWNER to postgres;
