CREATE TABLE IF NOT EXISTS public."Categories"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    last_updated timestamp without time zone DEFAULT now(),
    name text  NOT NULL,
    description text,
    category_type text,
    color_hex text,
    CONSTRAINT "Categories_pkey" PRIMARY KEY (id),
    CONSTRAINT "Categories_name_key" UNIQUE (name)
)


CREATE TABLE IF NOT EXISTS public."People"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    last_updated timestamp without time zone DEFAULT now(),
    first_name text not NULL,
    last_name text not NULL,
    short_name text not NULL,
    sms_number bigint,
    email_address text,
    comment text,
    CONSTRAINT "People_pkey" PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS public."Status"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    last_updated timestamp without time zone DEFAULT now(),
    name text NOT NULL,
    description text,
    status_type text,
    CONSTRAINT "status_pkey" PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS public."Tasks"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    last_updated timestamp without time zone DEFAULT now(),
    description text,
    due_date timestamp without time zone,
    comments text,
    assigned_to bigint,
    prerequisite_id bigint,
    category_id bigint not NULL,
    status_id bigint not NULL,
    CONSTRAINT "Tasks_pkey" PRIMARY KEY (id),
    CONSTRAINT "Tasks_description_key" UNIQUE (description),
    CONSTRAINT "Tasks_assigned_to_fkey" FOREIGN KEY (assigned_to)
        REFERENCES public."People" (id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "Tasks_prerequisite_id_fkey" FOREIGN KEY (prerequisite_id)
        REFERENCES public."Tasks" (id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "Tasks_category_id_fkey" FOREIGN KEY (category_id)
        REFERENCES public."Categories" (id)
        ON UPDATE RESTRICT
        ON DELETE NO action,
     CONSTRAINT "Tasks_status_id_fkey" FOREIGN KEY (status_id)
        REFERENCES public."Status" (id)
        ON UPDATE RESTRICT
        ON DELETE NO ACTION     
)