CREATE TABLE IF NOT EXISTS public."Categories"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    last_updated timestamp without time zone DEFAULT now(),
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    category_type text COLLATE pg_catalog."default",
    CONSTRAINT "Categories_pkey" PRIMARY KEY (id),
    CONSTRAINT "Categories_name_key" UNIQUE (name)
)

TABLESPACE pg_default;

ALTER TABLE public."Categories"
    OWNER to postgres;
