CREATE TABLE IF NOT EXISTS public."Tasks"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    last_updated timestamp without time zone DEFAULT now(),
    description text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    due_date timestamp without time zone,
    assigned_to bigint,
    comments text COLLATE pg_catalog."default",
    category_id bigint,
    CONSTRAINT "Tasks_pkey" PRIMARY KEY (id),
    CONSTRAINT "Tasks_description_key" UNIQUE (description),
    CONSTRAINT "Tasks_assigned_to_fkey" FOREIGN KEY (assigned_to)
        REFERENCES public."People" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "Tasks_category_id_fkey" FOREIGN KEY (category_id)
        REFERENCES public."Categories" (id) MATCH SIMPLE
        ON UPDATE RESTRICT
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public."Tasks"
    OWNER to postgres;
